Extended guild classes
powercord-org/powercord pull request #229
Opened 2019-09-10 13:21 UTC by cloudrac3r

Closes #215. This doesn't address the comment about guild names.

If you want to optimise out the ClassList thing into string matching functions then go ahead, but JS is fast so I don't care enough to do it myself.

The render function is called on a guild (and only that guild) when it is hovered or selected, which was very convenient for the creation of this plugin.

2019-09-10 14:07 UTC, cloudrac3r commented
fuck you eslint i do what i want

2019-09-10 20:41 UTC, cyyynthia requested changes

2019-09-10 20:41 UTC, Bowser65 commented on src/Powercord/plugins/pc-guild-classes/index.js
> +        const classList = new ClassList(res.props.className);
is an extra class required? Wouldn't something like this enough?
```js
const classNames = [ ...new Set(className.split(' ')) ]
hovered && classNames.push('...')
selected && classNames.push('...')
res.props.className = classNames.join(' ');
```

2019-09-10 20:41 UTC, Bowser65 commented on src/Powercord/plugins/pc-guild-classes/index.js
> +    const guildInner = await waitFor('.blobContainer-239gwq');
Avoid using raw classes in here, fetch them dynamically

2019-09-10 20:41 UTC, Bowser65 commented on src/Powercord/plugins/pc-guild-classes/index.js
> +    inject('cadence-guild-classes', Guild.constructor.prototype, 'render', (_, res) => {
Keeping injection names in here with "pc-" would be more consistent as it's an internal plugin

2019-09-10 20:41 UTC, Bowser65 commented on src/Powercord/plugins/pc-guild-classes/index.js
> +        classList.conditional(hovered, 'pgc-hovered');
is a prefix really required here? wouldn't just go for .hovered be enough?

2019-09-28 10:09 UTC, GriefMoDz approved these changes

2019-09-28 10:09 UTC, merged