Cache JSX transformations
powercord-org/powercord pull request #264
Opened 2019-11-18 06:46 UTC by intrnl

Improves subsequent JSX requires by [up to 48 percent](https://haste.powercord.dev/muhapohove.txt)

2019-11-18 08:02 UTC, intrnl commented
This caching implementation does not have a mapping of file names to their respective cache files, so this will be painful when developing as suddenly there would be a lot of trash generated.

Since I don't think adding mappings would add any performance penalties, I'm thinking of baking that in right now. 👍

2019-11-20 10:47 UTC, intrnl commented
Welp, I don't think having mappings is worth the effort considering the edge cases that comes along with it. So I'd say this is good to go.

2019-11-21 23:45 UTC, intrnl commented
Well it seems that the CI is failing thanks to an unrelated file

2019-11-22 10:53 UTC, Zerthox commented
The additional generated trash during development should be pretty small, since the only scenarios where it'll transform the same content is when the file has been modified but the contents haven't changed or have been reverted to an already cached state.

For further trash reduction the following ideas might be worth considering:
1. Make the cache clean itself. Remove already cached instances of a file on transform. This would also remove old files when Powercord updates, but it requires mappings.
2. Add an option to disable caching. This might be worth implementing for users who are short on disk space aswell.
3. Add a command to clear (or clean) the cache. This would be a little annoying to use during development, but it would also give end users more control over the cache.

2019-11-22 21:03 UTC, cyyynthia requested changes

2019-11-22 21:03 UTC, cyyynthia commented on src/Powercord/modules/jsx.js
> +const cacheDir = join(__dirname, '../../../cache/jsx/');
gitignore mentions `.cache` but you use `cache`
```suggestion
const cacheDir = join(__dirname, '../../../.cache/jsx/');
```

2019-11-22 21:03 UTC, Bowser65 commented on src/Powercord/modules/jsx.js
> +          console.error('[JSX]', 'Failed to write to cache');
Pretty:tm: logging
```suggestion
          console.error('%c[Powercord:JSX]', 'color: #7289da', 'Failed to write to cache');
```

2019-11-23 19:03 UTC, cyyynthia approved these changes

2019-11-23 19:04 UTC, merged