spanish translations
powercord-org/powercord pull request #289
Opened 2020-02-01 21:10 UTC by kablekompany

2020-02-01 21:17 UTC, cyyynthia requested changes

2020-02-01 21:17 UTC, Bowser65 commented on i18n/es-ES.json
> +  "POWERCORD_SETTINGS_NO_CLYDE_DESC": "Reemplaza a [Clyde] ({discordiaUrl}) en los comandos de Powercord con una gama mixta de avatares y nombres de usuario seleccionados por los desarrolladores de c
Space should be removed
```suggestion
  "POWERCORD_SETTINGS_NO_CLYDE_DESC": "Reemplaza a [Clyde]({discordiaUrl}) en los comandos de Powercord con una gama mixta de avatares y nombres de usuario seleccionados por los desarrolladores de complementos; retrocede a \"Powercord\" de forma predeterminada.",
```

2020-02-01 21:17 UTC, Bowser65 commented on i18n/es-ES.json
> +  "POWERCORD_SETTINGS_DISCORD_EXPERIMENTS_DESC": "****ADVERTENCIA:**** Habilitar esto le da acceso a funciones que Discord puede detectar y que pueden provocar la cancelación de una cuenta****. Power
Missing some *
```suggestion
  "POWERCORD_SETTINGS_DISCORD_EXPERIMENTS_DESC": "****ADVERTENCIA:**** Habilitar esto le da acceso a funciones que Discord puede detectar y que pueden provocar la ****cancelación de una cuenta****. Powercord **no es responsable** de lo que haces con esta función. Déjelo desactivado si no está seguro. El equipo de Powercord **no brindará asistencia** con respecto a cualquier experimento.",
```

2020-02-01 21:17 UTC, Bowser65 commented on i18n/es-ES.json
> +  "POWERCORD_SETTINGS_CACHE_CLEARED": "Caché despejado!",
I'm not an expert at spanish, but should this begin with an upside down `!`?

2020-02-01 21:17 UTC, Bowser65 commented on i18n/es-ES.json
> +  "POWERCORD_UPDATES_CHECKING": "Buscando actualizaciones ... ",
Space before ...

2020-02-01 21:17 UTC, Bowser65 commented on i18n/es-ES.json
> +  "POWERCORD_UPDATES_UPDATING": "Actualizando Powercord ...",
Space before ...

2020-02-01 21:17 UTC, Bowser65 commented on i18n/es-ES.json
> +  "POWERCORD_LINKING_ERRORED": "Se produjo un error. Verifique la consola para obtener más detalles y, por favor, [repórtelo] ({newIssueUrl}) si vuelve a ocurrir.",
Space should be removed
```suggestion
  "POWERCORD_LINKING_ERRORED": "Se produjo un error. Verifique la consola para obtener más detalles y, por favor, [repórtelo]({newIssueUrl}) si vuelve a ocurrir.",
```

2020-02-02 00:38 UTC, kablekompany reviewed
Suggested committed, other changes made

2020-02-02 00:39 UTC, cyyynthia approved these changes

2020-02-02 00:40 UTC, merged