Like command
powercord-org/powercord pull request #350
Opened 2020-06-28 09:36 UTC by StavZ

I added a like command to pc-spotify plugin which allows add current playing song to liked songs

2020-06-28 12:59 UTC, cyyynthia requested changes
The command doesn't take into account if the account is from Discord or Powercord. We can only update someone's library if they linked their account to Powercord since we need some extra scopes Discord doesn't request. See [this](https://github.com/powercord-org/powercord/blob/v2-dev/src/Powercord/plugins/pc-spotify/components/Modal.jsx#L160-L168) for an example on how to check this.

2020-06-28 13:02 UTC, StavZ commented
Ok. I'll fix it

2020-06-28 14:26 UTC, ohlookitsderpy commented on src/Powercord/plugins/pc-spotify/commands/like.js
> +        result: 'You need a [powercord](https://powercord.dev/) account and connected Spotify account.'
Powercord should be capitalised here

2020-06-28 15:50 UTC, davidcralph approved these changes

2020-06-28 23:38 UTC, cyyynthia requested changes

2020-06-28 23:38 UTC, Bowser65 commented on src/Powercord/plugins/pc-spotify/commands/like.js
> +    }
It'd be better to check for the Powercord account first
```suggestion
    if (!powercord.account && powercord.account.spotify) {
      return {
        send: false,
        result: 'You need a Powercord account and connected Spotify account.'
      };
    }
    const currentTrack = playerStore.getCurrentTrack();
    if (!currentTrack) {
      return {
        send: false,
        result: 'You are not currently listening to anything.'
      };
    }
```

2020-06-28 23:38 UTC, Bowser65 commented on src/Powercord/plugins/pc-spotify/commands/like.js
> +        result: `You removed **${currentTrack.name} by ${currentTrack.artists}** from your Liked Songs`
Styling nitpicking
```suggestion
        result: `You removed **${currentTrack.name}** by **${currentTrack.artists}** from your Liked Songs`
```

2020-06-28 23:38 UTC, Bowser65 commented on src/Powercord/plugins/pc-spotify/commands/like.js
> +      result: `You added **${currentTrack.name} by ${currentTrack.artists}** to your Liked Songs`
Styling nitpicking
```suggestion
      result: `You added **${currentTrack.name}** by **${currentTrack.artists}** to your Liked Songs`
```

2020-08-11 18:04 UTC, cyyynthia approved these changes

2020-08-11 18:04 UTC, merged