adding npm run update... (tot tested in an linux maschine...)
powercord-org/powercord pull request #558
Opened 2021-10-09 11:32 UTC by Blazzycrafter

using one dependencie and one file i have added an command...

kills discord via fkill an crossplatform kill command (NOT TESTED ON LINUX MAC...) LINK: https://github.com/sindresorhus/fkill
npm run unplug
git pull
npm i
npm run plug

2021-10-09 11:37 UTC, Blazzycrafter commented on package.json
> +    "update": "node injectors/fkill.js; npm run unplug && git pull && npm i && npm run plug"
ERROR: node injectors/fkill.js;  the  simicolon xD

2021-10-09 11:41 UTC, Blazzycrafter commented on package.json
> +
Remove NL
```suggestion
```

2021-10-09 11:42 UTC, Blazzycrafter commented on package.json
> +    "fkill":"7.2.1"
Formmatting
```suggestion
    "fkill": "7.2.1"
```

2021-10-09 11:43 UTC, Blazzycrafter reviewed
i remove my found "issues"

2021-10-10 20:31 UTC, pythonmcpi requested changes
Currently only works on Windows. See my comment in `injectors/fkill.js`.

2021-10-10 20:31 UTC, pythonmcpi commented on injectors/fkill.js
> +	await fkill("DiscordCanary.exe", {"force": true, "tree": true});
This line will not work on Mac or Linux. The Discord Canary binary's filename does not end with .exe on non-Windows platforms. I would recommend changing the target process name based on the user's platform.

Also, the `force` option should be `false`. If `force` is enabled, (at least on MacOS and Linux) the process will be terminated without allowing it to clean up (since a SIGKILL is sent instead of a SIGTERM). See [this Stack Exchange post](https://unix.stackexchange.com/a/281440) for more information on why you shouldn't use SIGKILL.

`silent` should probably be set to `true` as well. If canary was not running, the user will see a 'Process not found.' without any explanations. The rest of the commands in the chain might not run either. (I'm not sure if node sets an error return code for errors in Promises.)

2021-10-10 20:31 UTC, pythonmcpi commented on package.json
> +    "fkill": "7.2.1"
Weight of the dependencies [before](https://bundlephobia.com/scan-results?packages=codemirror@5.57.0,less@3.12.2,node-watch@0.6.4,sass@1.35.2,stylus@0.54.8,sucrase@3.15.0,unzip-crx@0.2.0&sortMode=size) and [after](https://bundlephobia.com/scan-results?packages=codemirror@5.57.0,less@3.12.2,node-watch@0.6.4,sass@1.35.2,stylus@0.54.8,sucrase@3.15.0,unzip-crx@0.2.0,fkill@7.2.1&sortMode=size) adding `fkill`. The difference is fairly small but considering that this is to support something that many Powercord users will not use, is it really necessary? Are there any better, more lightweight alternatives? (The answer might be no, more research needs to be done on package options.)

2021-10-10 20:33 UTC, pythonmcpi commented on package.json
> +    "update": "node injectors/fkill.js npm run unplug && git pull && npm i && npm run plug"
The `&&` between the `node injectors/fkill.js` and `npm run unplug` seems to be missing.

2021-11-09 03:54 UTC, Blazzycrafter commented
reason:
i dont work anymore at this...

2021-11-09 03:54 UTC, closed without merging