Add commands for plugging stable and PTB
powercord-org/powercord pull request #633
Opened 2022-04-25 03:20 UTC by asportnoy

This adds commands for installing to Stable or PTB. This can be done by appending a version to the command: `npm run <plug|unplug> [stable|ptb|canary]`. A warning will be given to the user and they will have to confirm before the install continues. 
<img width="927" alt="Screenshot on 2022-04-24 at 22 13 23" src="https://user-images.githubusercontent.com/14863373/165015251-574cea99-4150-4d3c-9bd4-047a472b4a9f.png">

I was only able to test injection on macOS. I was able to find the windows paths [here](https://www.reddit.com/r/discordapp/comments/dhiovp/comment/f3ofvrl/?utm_source=share&utm_medium=web2x&context=3) but I had to guess the Linux paths based on context.

I updated the info in the README, but the wiki still needs to be updated. You might want to move the README info to the wiki instead of where it currently is, but that is up to you. The information in the Discord server probably needs to be updated as well.

Closes #632

2022-04-25 05:53 UTC, Captain8771 commented
is there any reason discordDevelopment isnt included?

2022-04-25 11:01 UTC, asportnoy commented
> is there any reason discordDevelopment isnt included?

As far as I know, there's no advantage discordDevelooment has and it's not supposed to be hard anyways

2022-04-25 11:47 UTC, kekkodance commented
> > is there any reason discordDevelopment isnt included?
> 
> As far as I know, there's no advantage discordDevelooment has and it's not supposed to be used anyways

it's not about "advantages". if a user chose that they needed powercord on dev (which would be basically the same as a canary instance) they would have to do the rudimentary method of changing a string in powercord's injector, which makes your PR useless. it's not hard to add a new "dev" instance in the choices.

2022-04-25 11:49 UTC, asportnoy commented
Alright. Let me know the install paths and the subdomain and I'll add it later today.

2022-04-25 11:51 UTC, kekkodance commented
the path for dev is just "DiscordDevelopment"

2022-04-25 11:52 UTC, asportnoy commented
And is it dev.discord.com? or development.discord.com?

2022-04-25 11:55 UTC, kekkodance commented
discord dev just points to canary, doesn't it? they offer the installer for dev here: https://discordapp.com/api/download/development?platform=win 
but they do not have another endpoint like ptb.discord.com / canary.discord.com etc.

2022-04-25 12:32 UTC, CanadaHonk commented
> discord dev just points to canary, doesn't it

Just to confirm, yes it just loads the normal canary webapp_endpoint (`https://canary.discord.com/app`).

2022-04-25 12:51 UTC, asportnoy commented
As with the other clients, I had to guess on the linux paths. But macOS and Windows should both be good.

2022-05-26 02:01 UTC, aetheryx requested changes

2022-05-26 02:01 UTC, aetheryx commented on injectors/index.js
> +      }
resolve(answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes')

2022-05-26 02:01 UTC, aetheryx commented on injectors/linux.js
> +};
freeze the entire object (`const KnownLinuxPaths = Object.freeze({ stable: [ ... ], ... })`) instead of each of the arrays

2022-05-26 02:01 UTC, aetheryx commented on injectors/linux.js
> +      console.log(`Please provide the path of your Discord${platform  == 'canary' ? ' Canary' : ''} installation folder`);
the platform should always be printed, just print something like `Failed to locate Discord (platform: ${platform})`

2022-05-26 18:07 UTC, aetheryx requested changes

2022-05-26 18:07 UTC, aetheryx commented on injectors/index.js
> +    })
missing semicolons

2022-05-26 18:07 UTC, aetheryx commented on injectors/linux.js
> +}
missing semicolon

2022-05-26 18:07 UTC, aetheryx commented on src/patcher.js
>    });
fix indentation

2022-05-27 01:11 UTC, katlyn approved these changes
All changes work on linux clients after cursory testing.

2022-05-27 14:26 UTC, asportnoy commented
Rebased

2022-06-01 22:56 UTC, merged