Integrate Theme Toggling
powercord-org/powercord pull request #634
Opened 2022-04-26 20:58 UTC by 12944qwerty

This literally took 2 minutes to do lol

If it needs anything else, just let me know I guess. I also kept the beta code in there in case anyone wanted it to stay there anyway :P

2022-04-27 18:49 UTC, 12944qwerty commented
BTW, don't merge yet.

I still have to add commands and fix uninstall buttons

2022-04-27 19:00 UTC, LandenStephenss commented on src/Powercord/plugins/pc-moduleManager/components/manage/Themes.jsx
> +          this.forceUpdate();
just make this a functional component where you pass some functions and use setState ??

2022-04-28 02:42 UTC, 12944qwerty commented
I've been trying for a bit and I'm unable to figure out how to fix the uninstall button.
I've added a bunch of errorhandlers and all, but I can't seem to figure out where the crash is happening.

I'll continue debugging, but just pull this request for now. I'll open a new one if I don't figure it out before this is pulled.

2022-06-18 23:54 UTC, asportnoy requested changes

2022-06-18 23:54 UTC, asportnoy commented on src/Powercord/plugins/pc-moduleManager/components/manage/Themes.jsx
> +// const FEEDBACK_IDENTIFIER = 3758304876382993109949n;
Why leave these commented? Just remove them if you don't need them.

2022-06-18 23:54 UTC, asportnoy commented on src/Powercord/plugins/pc-moduleManager/components/manage/Themes.jsx
> +// }
Same as above

2022-06-18 23:54 UTC, asportnoy commented on src/Powercord/plugins/pc-moduleManager/components/manage/Themes.jsx
> +  // }
Same as above

2022-06-19 19:47 UTC, asportnoy approved these changes

2022-07-13 03:31 UTC, asportnoy requested changes

2022-07-13 03:31 UTC, asportnoy commented on package.json
> -    "eslint": "^7.8.1",
What was the reason for this update?

2022-07-13 03:31 UTC, asportnoy commented on src/Powercord/plugins/pc-moduleManager/commands/enable.js
> +  description: 'Allows you to re-/enable a selected plugin/theme from the given list.',
```suggestion
  description: 'Enable a plugin/theme',
```

2022-07-13 03:31 UTC, asportnoy commented on src/Powercord/plugins/pc-moduleManager/commands/disable.js
> +  description: 'Allows you to disable a selected plugin/theme from the given list.',
```suggestion
  description: 'Disable a plugin/theme',
```

2022-07-13 03:31 UTC, asportnoy commented on src/Powercord/plugins/pc-moduleManager/commands/disable.js
> +        })) ],
You should try to reduce the amount of duplicate code in this function.

2022-07-13 03:31 UTC, asportnoy commented on src/Powercord/plugins/pc-moduleManager/commands/enable.js
> +        })) ],
You should try to reduce the amount of duplicate code in this function.

2022-07-20 12:55 UTC, aetheryx commented
reopened @ https://github.com/powercord-org/powercord/pull/670

2022-07-20 12:55 UTC, closed without merging