For the love of god.
powercord-org/powercord pull request #662
Opened 2022-07-01 18:41 UTC by ma1ted

Hold it together for fuck's sake

2022-07-01 18:52 UTC, kekkodance commented
the best client mod ever

2022-07-01 18:55 UTC, SlippingGitty commented
![2tbwf7](https://user-images.githubusercontent.com/76500838/176954303-9f19c61f-d2c2-4168-abb3-5622e96e932e.png)

2022-07-01 19:33 UTC, HonbraDev commented
fucky wucky better imo

2022-07-01 19:35 UTC, Captain8771 commented
I disagree with this pull request, why? Well you see I use Arch Linux and its great. it might be very hard at first, but you will get used to it. You see, Arch Linux is a very lightweight operating system. It doesn't come with bloatware pre installed, which is great, but it doesn't come with a desktop environment pre installed which is kind of sad to be honest. But, I can just install it myself, and enjoy using my computer.

Oh, and I agree with what the above person said.

2022-07-01 22:49 UTC, Craftzman7 commented
I agree with what the above person said.

2022-07-02 09:26 UTC, zplusfour commented
I AGREE WITH MALTED

2022-07-02 09:27 UTC, CoolCoderSJ commented
fucky wucky way faster to recgonize tho

2022-07-02 09:31 UTC, ma1ted commented
I'd just like to interject for a moment. What you're refering to as fucky wucky, is in fact, GNU/fucky wucky, or as I've recently taken to calling it, GNU plus fucky wucky. fucky wucky is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.

Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called fucky wucky, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.

There really is a fucky wucky, and these people are using it, but it is just a part of the system they use. fucky wucky is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. fucky wucky is normally used in combination with the GNU operating system: the whole system is basically GNU with fucky wucky added, or GNU/fucky wucky. All the so-called fucky wucky distributions are really distributions of GNU/fucky wucky!

2022-07-02 09:41 UTC, zplusfour commented
merge this pr or i will tell dwayne johnson to not twerk on your birthdays

2022-07-02 09:48 UTC, Captain8771 commented
do not merge this pr

2022-07-02 09:55 UTC, Shylke commented
Made your copypasta better:

I'd just wike to intewject fow a moment. What you'we wefewwing to as fucky wucky, is in fact, gnu/fucky wucky, ow as i've wecentwy taken to cawwing it, gnu pwus fucky wucky. fucky wucky is not an opewating system unto itsewf, but wathew anothew fwee component of a fuwwy functioning gnu system made usefuw by the gnu cowewibs, sheww utiwities and vitaw system components compwising a fuww os as defined by posix.

many computew usews wun a modified vewsion of the gnu system evewy day, without weawizing it. Thwough a pecuwiaw tuwn of events, the vewsion of gnu which is widewy used today is often cawwed "fucky wucky", and many of its usews awe not awawe that it is basicawwy the gnu system, devewoped by the gnu pwoject.

thewe weawwy is a fucky wucky and these peopwe awe using it, but it is just a pawt of the system they use. fucky wucky is the kewnew: the pwogwam in the system that awwocates the machine's wesouwces to the othew pwogwams that you wun. the kewnew is an essentiaw pawt of an opewating system, but usewess by itsewf; it can onwy function in the context of a compwete opewating system. fucky wucky is nowmawwy used in combination with the gnu opewating system: the whowe system is basicawwy gnu with fucky wucky added, ow gnu/fucky wucky . Aww the so-cawwed "fucky wucky" distwibutions awe weawwy distwibutions of gnu/fucky wucky.


Also pls dont merge the pr

2022-07-02 09:56 UTC, Captain8771 commented
Jesus Christ

2022-07-02 11:38 UTC, aetheryx commented
:blobpopcorn:

2022-07-02 16:54 UTC, Captain8771 requested changes
changing the message to fucky wucky would be beneficial to the economy, could you implement that?

2022-07-02 17:06 UTC, Captain8771 requested changes
could this be inplemented

2022-07-02 17:06 UTC, Captain8771 commented on injectors/index.js
> +    console.error('An unknown error occured. Please try again.', e);
```suggestion
    console.error('fucky wucky', e);
```

2022-07-06 16:19 UTC, cnnrde commented on injectors/index.js
> +    console.error('An unknown error occured. Please try again.', e);
this implementation would be beneficial to the economy

2022-07-06 19:39 UTC, Captain8771 commented on injectors/index.js
> +    console.error('An unknown error occured. Please try again.', e);
it would also delete NFT's

2022-07-06 22:30 UTC, MulverineX commented
blame:
![image](https://user-images.githubusercontent.com/12068027/177654117-29e3096b-1ddb-4d2d-84e3-998402214824.png)

2022-07-27 20:50 UTC, dox-net commented on injectors/index.js
> +    console.error('An unknown error occured. Please try again.', e);
```suggestion
    console.error('Uh oh we made a fucky wucky UwU, Pwease try again X3', e);
```

2022-07-28 07:40 UTC, zplusfour commented
tf

2023-02-20 21:37 UTC, hayden-droid approved these changes

2023-02-21 19:50 UTC, zoey-on-github commented
fucky wucky ftw

On Mon, Feb 20, 2023 at 1:38 PM Descendo The Monkei <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/powercord-org/powercord/pull/662#pullrequestreview-1306358530>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVFRGK2Z7SOHLURIIMDQWFTWYPP37ANCNFSM52NQ4PCA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-02-27 18:44 UTC, Haprus approved these changes
I agree.

2023-03-01 23:06 UTC, closed without merging

2023-03-01 23:23 UTC, Craftzman7 commented
peace at last

2023-03-02 00:05 UTC, ma1ted commented
heh

2023-03-02 05:47 UTC, Captain8771 commented
NOOOOOOOOOO

2023-03-02 18:09 UTC, HonbraDev commented
> NOOOOOOOOOO

yes!